#!/usr/bin/env python3
#///\\\ "0" ///\\\

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk
import subprocess
import shutil
import os
import getpass

class UiLayout(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title="OpenVPN")
        self.set_default_size(500, 800)
        self.set_position(Gtk.WindowPosition.CENTER_ALWAYS)
        self.set_resizable(False)
        fixed = Gtk.Fixed()
        self.add(fixed)
        
        image = Gtk.Image.new_from_file("Images/ovpn_Profiles.jpeg")
        fixed.put(image, 0, 0)

        overlay = Gtk.Overlay()
        overlay.set_size_request(500, 800)
        fixed.put(overlay, 0, 0)

        button_image = Gtk.Image.new_from_file("Images/ovpn_settings.png")
        button = Gtk.Button()
        button.connect("clicked", self.on_settings_button_clicked)
        button.add(button_image)
        overlay.add_overlay(button)
        overlay.set_overlay_pass_through(button, True)
        button.set_margin_start(20)
        button.set_margin_top(20)
        button.set_valign(Gtk.Align.START)
        button.set_halign(Gtk.Align.START)

        button_image2 = Gtk.Image.new_from_file("Images/ovpn_scroll.png")
        button2 = Gtk.Button()
        button2.connect("clicked", self.on_button2_clicked)
        button2.add(button_image2)
        overlay.add_overlay(button2)
        overlay.set_overlay_pass_through(button2, True)
        button2.set_margin_end(20)
        button2.set_margin_top(20)
        button2.set_valign(Gtk.Align.START)
        button2.set_halign(Gtk.Align.END)

        button_image3 = Gtk.Image.new_from_file("Images/ovpn_plus.png")
        button3 = Gtk.Button()
        button3.connect("clicked", self.on_button3_clicked)
        button3.add(button_image3)
        overlay.add_overlay(button3)
        overlay.set_overlay_pass_through(button3, True)
        button3.set_margin_end(20)
        button3.set_margin_bottom(20)
        button3.set_valign(Gtk.Align.END)
        button3.set_halign(Gtk.Align.END)

##############################################################################

        # Create the main box to hold the switches
        switch_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=20)

        # Create and add the first switch
#        switch_with_label_button1 = self.create_switch_with_label_button("Label for Switch 1")
#        switch_box.pack_start(switch_with_label_button1, False, False, 0)

        # Create and add the second switch
#        switch_with_label_button2 = self.create_switch_with_label_button("Label for Switch 2")
#        switch_box.pack_start(switch_with_label_button2, False, False, 0)

#        switch_with_label_button3 = self.create_switch_with_label_button("Label for Switch 2")
#        switch_box.pack_start(switch_with_label_button3, False, False, 0)

#        switch_with_label_button4 = self.create_switch_with_label_button("Label for Switch 2")
#        switch_box.pack_start(switch_with_label_button4, False, False, 0)

#        switch_with_label_button5 = self.create_switch_with_label_button("Label for Switch 2")
#        switch_box.pack_start(switch_with_label_button5, False, False, 0)

#///\\\ "END" ///\\\
        # Add the switch box to the overlay
        overlay.add_overlay(switch_box)
        switch_box.set_valign(Gtk.Align.CENTER)
        switch_box.set_halign(Gtk.Align.CENTER)

        self.show_all()

    def create_switch_with_label_button(self, label_text):
        switch_with_label_button = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        switch = Gtk.Switch()
        label = Gtk.Label(label=label_text)

        switch_with_label_button.pack_start(switch, False, False, 0)
        switch_with_label_button.pack_start(label, False, False, 0)

        return switch_with_label_button

##############################################################################

    def css():
        css_provider = Gtk.CssProvider()
        css_provider.load_from_path("styles.css")

        context = Gtk.StyleContext()
        screen = Gdk.Screen.get_default()
        context.add_provider_for_screen(screen, css_provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)

        ui_layout = UiLayout()
        ui_layout.connect("destroy", Gtk.main_quit)
        ui_layout.show_all()
        Gtk.css()

        if __name__ == "__main__":
            css()


    def show_error_dialog(self, message):
        dialog = Gtk.MessageDialog(
            parent=self,
            flags=0,
            message_type=Gtk.MessageType.ERROR,
            buttons=Gtk.ButtonsType.OK,
            text=message,
        )
        dialog.run()
        dialog.destroy()

##############################################################################
############################# SETTINGS WINDOW ################################
##############################################################################

    def on_settings_button_clicked(self, button):
        settings_window = Gtk.Window(title="Settings")
        settings_window.set_default_size(500, 800)
        settings_window.set_position(Gtk.WindowPosition.CENTER_ON_PARENT)
        settings_window.set_transient_for(self)
        settings_window.set_resizable(False)

        overlay = Gtk.Overlay()
        settings_window.add(overlay)
        
        settings_image = Gtk.Image.new_from_file("Images/ovpn_settings.jpeg")
        overlay.add(settings_image)
        
        fixed = Gtk.Fixed()
        overlay.add_overlay(fixed)

        button_image = Gtk.Image.new_from_file("Images/ovpn_arrow.png")  # Replace with the path to your button image
        button = Gtk.Button()
        button.connect("clicked", self.on_back_to_main_clicked, settings_window)
        button.add(button_image)
        overlay.add_overlay(button)
        overlay.set_overlay_pass_through(button, True)
        button.set_margin_start(20)
        button.set_margin_top(20)
        button.set_valign(Gtk.Align.START)
        button.set_halign(Gtk.Align.START)

        settings_window.connect("destroy", Gtk.main_quit)

        settings_window.show_all()

        self.hide()

    def on_back_to_main_clicked(self, button, settings_window):
        settings_window.hide()
        self.show_all()

##############################################################################
############################### LOGS WINDOW ##################################
##############################################################################
    def get_logs_output(self):
        result = subprocess.run(['pkexec', 'journalctl', '-u', 'openvpn.service'], capture_output=True, text=True)
        return result.stdout.strip() if result.stdout else ""

    def on_button2_clicked(self, button):
        logs_window = Gtk.Window(title="Logs")
        logs_window.set_default_size(500, 800)
        logs_window.set_position(Gtk.WindowPosition.CENTER_ON_PARENT)
        logs_window.set_transient_for(self)
        logs_window.set_resizable(False)

        overlay = Gtk.Overlay()
        logs_window.add(overlay)

        logs_image = Gtk.Image.new_from_file("Images/ovpn_logs.jpeg")
        overlay.add_overlay(logs_image)

        scrolled_window = Gtk.ScrolledWindow()
        scrolled_window.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)
        overlay.add_overlay(scrolled_window)

        fixed = Gtk.Fixed()
        scrolled_window.add(fixed)

        button_image = Gtk.Image.new_from_file("Images/ovpn_arrow.png")
        button = Gtk.Button()
        button.connect("clicked", self.on_back_to_main_clicked, logs_window)
        button.add(button_image)
        overlay.add_overlay(button)
        overlay.set_overlay_pass_through(button, True)
        button.set_margin_start(20)
        button.set_margin_top(20)
        button.set_valign(Gtk.Align.START)
        button.set_halign(Gtk.Align.START)

        logs_output = self.get_logs_output()
        logs_label = Gtk.Label()
        logs_label.set_text(logs_output)
        logs_label.set_line_wrap(True)  # Enable line wrapping
        
        logs_label_x = 100
        logs_label_y = 100
        fixed.put(logs_label, logs_label_x, logs_label_y)

        logs_window.connect("destroy", Gtk.main_quit)
        logs_window.show_all()
        self.hide()

    def on_back_to_main_clicked(self, button, logs_window):
        logs_window.hide()
        self.show_all()

##############################################################################
############################### ADD WINDOW ##################################
##############################################################################

    def on_button3_clicked(self, button):
        add_window = Gtk.Window(title="ADD")
        add_window.set_default_size(500, 800)
        add_window.set_position(Gtk.WindowPosition.CENTER_ON_PARENT)
        add_window.set_transient_for(self)
        add_window.set_resizable(False)

        overlay = Gtk.Overlay()
        add_window.add(overlay)

        add_image = Gtk.Image.new_from_file("Images/ovpn_Import.jpeg")
        overlay.add(add_image)

        fixed = Gtk.Fixed()
        overlay.add_overlay(fixed)

        button_image = Gtk.Image.new_from_file("Images/ovpn_arrow.png")
        button = Gtk.Button()
        button.connect("clicked", self.on_back_to_main_clicked, add_window)
        button.add(button_image)
        overlay.add_overlay(button)
        overlay.set_overlay_pass_through(button, True)
        button.set_margin_start(20)
        button.set_margin_top(20)
        button.set_valign(Gtk.Align.START)
        button.set_halign(Gtk.Align.START)

        add_button_image2 = Gtk.Image.new_from_file("Images/ovpn_browse.png")
        add_button = Gtk.Button()
        add_button.connect("clicked", self.on_add_button_clicked, add_window)  # Pass add_window as an argument
        add_button.add(add_button_image2)
        overlay.add_overlay(add_button)
        overlay.set_overlay_pass_through(add_button, True)
        add_button.set_margin_end(20)
        add_button.set_margin_top(20)
        add_button.set_valign(Gtk.Align.CENTER)
        add_button.set_halign(Gtk.Align.CENTER)
        add_button.set_margin_top(350)
        add_button.set_margin_start(20)

        add_window.connect("destroy", Gtk.main_quit)

        add_window.show_all()

        self.hide()

    def on_add_button_clicked(self, button, add_window):
        dialog = Gtk.FileChooserDialog(
            title="Select a file Hoss",
            parent=self,
            action=Gtk.FileChooserAction.OPEN,
            buttons=(
                Gtk.STOCK_CANCEL,
                Gtk.ResponseType.CANCEL,
                Gtk.STOCK_OPEN,
                Gtk.ResponseType.OK,
            ),
        )
        response = dialog.run()

        if response == Gtk.ResponseType.OK:
            selected_file_path = dialog.get_filename()
            print("You clicked the OK button")
            print("File selected: " + selected_file_path)
            
            # Copy the selected file to /etc/openvpn
            try:
                script_path = "/opt/OpenVPN/scripts/add.sh"  # Replace with the actual path to your script
                destination_path = "/etc/openvpn/.ovpn" + os.path.basename(selected_file_path)
                command = ["pkexec", "bash", script_path, selected_file_path, destination_path]
                subprocess.run(command, check=True)
                self.show_error_dialog("File copied to /etc/openvpn successfully!")
            except FileNotFoundError:
                self.show_error_dialog("Error: File not found.")
            except PermissionError:
                self.show_error_dialog("Error: Permission denied. Make sure you have administrative privileges.")
            except Exception as e:
                self.show_error_dialog("Error: Not the correct file! Needs to be a .ovpn file")
        elif response == Gtk.ResponseType.CANCEL:
            self.show_error_dialog("User didn't choose any file")
        dialog.destroy()

ui_layout = UiLayout()
ui_layout.connect("destroy", Gtk.main_quit)
ui_layout.show_all()
Gtk.main()
